name: Publish package to PyPi

on:
  release:
    types: [published]

jobs:

  push:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        dir: ['python_app_1', 'python_app_2']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install pip
        run: pip install pip

      - name: Install Dependencies
        run: pip install setuptools wheel

      - name: Build package
        working-directory: ${{ matrix.dir }}
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ matrix.dir }}
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD_TOKEN }}

