name: Upgrade Python Requirements

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch against which to create requirements PR"
        required: true
        default: 'master'

jobs:
  call-upgrade-python-requirements-workflow:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        dir: ['python_app_1', 'python_app_1']
    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - uses: actions/checkout@v4

      - name: make upgrade
        working-directory: ${{ matrix.dir }}
        run: |
          pip install pip pip-compile
          pip-compile --upgrade -o requirements/base.txt requirements/base.in
    # Do not run on forks
    # if: github.repository == 'irtazaakram/monorepo'
    # run:
    #   pip install pip-compile
    # uses: openedx/.github/.github/workflows/upgrade-python-requirements.yml@master
    # with:
    #   branch: ${{ github.event.inputs.branch || 'master' }}
    #   # optional parameters below; fill in if you'd like github or email notifications
    #   # user_reviewers: ""
    #   team_reviewers: "axim-aximprovements"
    #   email_address: "aximimprovements@axim.org"
    #   send_success_notification: false
    # secrets:
    #   requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
    #   requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
    #   edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
    #   edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
